---
title: "Reproduction File"
output: html_document
---

All scripts required to reproduce the figures and tables in *Differential privacy in the 2020 Census distorts COVID-19 rates* are contained below.


```{r echo=FALSE}
rm(list=ls())
library(knitr)
read_chunk('../R/SCRIPTS/000-Libraries.R')
read_chunk('../R/SCRIPTS/001-DataLoad.R')
read_chunk('../R/SCRIPTS/102-PopulationPyramid.R')
read_chunk('../R/SCRIPTS/102-FigureAgeSex.R')
read_chunk('../R/SCRIPTS/103-FigureRace.R')
read_chunk('../R/SCRIPTS/table1.R')
```
# Libraries Required

```{r libraries, echo=TRUE, message=FALSE, warning=FALSE, cache=FALSE}

```

# Data Load and Manipulation
```{r DataLoad, echo=TRUE, message = FALSE, warning = FALSE, cache=FALSE} 
```

# Figures
<!-- ## Population Pyramid -->

<!-- ```{r PopPyramid, echo=TRUE, message = FALSE, warning = FALSE, cache=FALSE, dev = c("png", "pdf"), dpi=300,fig.cap= paste("Changes in population pyramids due to the implementation of differential privacy in 2010 U.S. Census data for six US counties. \\label{fig-poppyramid}")}  -->
<!-- ``` -->

## Age-Sex Specific Figure

```{r FigureAgeMultipanel, echo=TRUE, message = FALSE, warning = FALSE, cache=FALSE, dev = c("png", "pdf"), dpi=300,fig.cap= paste("The distortion of COVID-19 age-sex specific mortality rates for US counties. We show only those county age-sex groups with less than 500% error. Red dots correspond to county age-sex groups with mortality rates that impossibly exceed 1.0. \\label{fig-agesex}")} 
```

## Race Specific Figure

```{r FigureRaceMultipanel, echo=TRUE, message = FALSE, warning = FALSE, cache=FALSE, dev = c("png", "pdf"), dpi=300,fig.cap= paste("The distortion of COVID-19 race-specific mortality rates for US counties. We show only those county race groups with less than 500% error. \\label{fig-race}")} 
```


```{r FigureCombined, echo=FALSE, message = FALSE, warning = FALSE, cache=FALSE, dev = c("png", "pdf")}
fig3
```

# Tables
## Table 1

```{r Table1, echo=TRUE, message = FALSE, warning = FALSE, cache=FALSE} 
```
